"""Pydantic models for assessments and rubrics generated by Pipeline 1."""

from __future__ import annotations

from pydantic import BaseModel, Field

from schemas.common_schema import AssessmentType, DifficultyLevel, GroundingStatus


class RubricCriterion(BaseModel):
    """One weighted rubric row."""

    criterion: str
    weight: float = Field(gt=0, le=1)
    expected_performance: str
    pass_condition: str


class Assessment(BaseModel):
    """Knowledge, practical, scenario, or role-specific assessment."""

    assessment_id: str
    title: str
    assessment_type: AssessmentType
    rubric: list[RubricCriterion] = Field(min_length=1)
    difficulty: DifficultyLevel
    stage: str
    source_document_id: str
    source_section_id: str
    requirement_ids: list[str] = Field(min_length=1)
    grounding_status: GroundingStatus = GroundingStatus.SOURCE_SUPPORTED
    pass_threshold: float = Field(gt=0, le=1, default=0.8)
