"""Pydantic models for learning modules and checklist items generated by Pipeline 1."""

from __future__ import annotations

from pydantic import BaseModel, Field

from schemas.common_schema import DifficultyLevel


class LearningModule(BaseModel):
    """One learning module in a generated onboarding plan."""

    module_id: str
    title: str
    purpose: str
    objectives: list[str] = Field(min_length=1)
    key_concepts: list[str] = Field(min_length=1)
    source_docs: list[str] = Field(min_length=1)
    source_document_id: str
    source_section_id: str
    duration_minutes: int = Field(gt=0)
    activities: list[str] = Field(min_length=1)
    assessment_method: str
    completion_criteria: str
    stage: str
    difficulty: DifficultyLevel
    requirement_ids: list[str] = Field(min_length=1)


class ChecklistItem(BaseModel):
    """One checklist activity tied to a source requirement."""

    item_id: str
    activity: str
    required_or_optional: str
    due_stage: str
    completion_status: str = "not_started"
    source_document_id: str
    source_section_id: str
    responsible_person: str
    requirement_id: str
