"""Pydantic models for quiz questions generated by Pipeline 1."""

from __future__ import annotations

from pydantic import BaseModel, Field

from schemas.common_schema import DifficultyLevel, DistractorValidationStatus, QuestionType


class QuizQuestion(BaseModel):
    """One sourced quiz item. Incorrect options must be plausible, not contradictory to the source."""

    question_id: str
    question_text: str
    question_type: QuestionType
    options: list[str] = Field(min_length=2)
    correct_answer: str | list[str]
    explanation: str
    source_document_id: str
    source_section_id: str
    difficulty: DifficultyLevel
    requirement_id: str
    distractor_validation_status: DistractorValidationStatus = DistractorValidationStatus.PENDING_VERIFICATION
    generation_status: str | None = None

